services:
  - type: web
    name: shijin-portfolio
    env: static
    buildCommand: chmod +x build.sh && ./build.sh
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html